blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>', views.detail, name='detail'),

    ]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),
    ]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models



# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.

def all_blogs(request):
    
    blogs = Blog.objects.order_by('-date')
    return render(request,'blog/all_blogs.html',{'blogs':blogs})


def detail(request,blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()

    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}
{% block content %}


<h1 class="blog-header">Blog</h1>
<h2 class="blog-dec blog-header">Sahasil has Written {{blogs.count}} blog{{blogs.count|pluralize}}</h2>
{% for blog in blogs  %}
<div class="jumbotron">
  <a class="blog-title" href="{% url 'blog:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
  <h5 class="blog-date">{{blog.date|date:'M d Y'|upper}}</h5>
  <p class="blog-dec">{{blog.description|truncatechars:100}}</p>

</div>

{% endfor %}
{% endblock content %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}
{% block content %}




  <h1 class="blog-title blog-header">{{blog.title}}</h1>

  <h2 class="blog-date dates">--{{blog.date|date:'F jS Y'}}--</h2>
<div class="jumbotron">
  <p class="blog-dec">{{blog.description|safe}}</p>

</div>





{% endblock content %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sahasil's Portfolio</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <ul class='navbar-nav mr-auto'>

      <li  class="nav-item"> <a href="{% url 'home' %}" class="navbar-brand mynav"> Sahasil</a> </li>

    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class='navbar-nav ml-auto'>


              <li class="nav-item"> <a class="nav-link mynav " href="{% static 'portfolio/resume.pdf' %}" target='_blank'>Resume</a></li>
              <li class="nav-item"> <a class="nav-link mynav" href="https://github.com/SahasilAK" target='_blank'>Github</a></li>
              <li class="nav-item"> <a class="nav-link mynav  " href="https://www.linkedin.com/in/sahasil-ak/" target='_blank'>Linkedin</a></li>
              <li class="nav-item blog-link"> <a class="nav-link mynav" href="{% url 'blog:all_blogs' %}">Blog</a> </li>

          </div>


           </ul>




    </nav>
    <div class="container">
{% block content %}

{% endblock %}
    </div>

  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">

    <img class="img-fluid myimage" src="{% static 'portfolio/prof.jpg' %}" alt="no img">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometex" class="font-weight-bold">Python Full Stack Developer</h1>
  </div>
</div>

<h1 class="blog-title mt-5">Portfolio</h1>
<hr>
<div class="row">
  {% for project in projects %}
    <div class="col-lg-4 col-md-6">

      {% if project.url  %}
          <a href="{{project.url}}" target="_blank">
            <img src="{{project.image.url}}" alt="project_img" class="img-fluid mb-2 proimg " >
          </a>


  {% else %}
        <img src="{{project.image.url}}" alt="project_img" class="img-fluid mb-2 proimg ">


  {% endif %}
      <h3 class="prot">{{project}}</h3>
      <p class="prod">{{project.description}}</p>




</div>




{% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-lg navbar-dark">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class='navbar-nav mr-auto'>
        <li class="navbar-brand mynav">Sahasil's Portfolio</li>
        <li> <a class="nav-link mynav" href="{% url 'blog:all_blogs' %}">Blog</a> </li>
        <li> <a class="nav-link mynav nav-right" href="{% static 'portfolio/resume.pdf' %}">Resume</a></li>
        <li> <a class="nav-link mynav" href="https://github.com/SahasilAK">Github</a></li>
        <li> <a class="nav-link mynav" href="https://www.linkedin.com/in/sahasil-ak/">Linkedin</a></li>

      </ul>

      </div>

    </nav>
    <div class="container">
{% block content %}

{% endblock content %}
    </div>

  </body>
</html>